name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud-analysis:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}  # Fixed secret name

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            backend/node_modules
            frontend/node_modules
          key: ${{ runner.os }}-${{ hashFiles('backend/package-lock.json', 'frontend/package-lock.json') }}

      - name: Install Backend Dependencies
        working-directory: backend
        run: npm ci --prefer-offline

      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm ci --prefer-offline

      - name: Run Backend Tests with Coverage
        working-directory: backend
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
        run: npm test -- --coverage

      - name: Run Frontend Tests with Coverage
        working-directory: frontend
        continue-on-error: true
        run: npm test -- --coverage

      - name: Verify Coverage Reports
        run: |
          [ -f backend/coverage/lcov.info ] || (echo "Backend coverage missing" && exit 1)
          [ -f frontend/coverage/lcov.info ] || (echo "Frontend coverage missing" && exit 1)

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v4.1.0
        with:
          args: >
            -Dsonar.organization=Mohamed-Redouane
            -Dsonar.projectKey=redouane
            -Dsonar.sources=backend,frontend
            -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**
            -Dsonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info
            -Dsonar.coverage.exclusions=**/test/**,**/__mocks__/**
            -Dsonar.qualitygate.wait=true
            -Dsonar.branch.name=${{ github.event.pull_request.head.ref || github.ref_name }}
            -Dsonar.branch.target=main
            -Dsonar.pullrequest.base=main
            -Dsonar.pullrequest.branch=${{ github.event.pull_request.head.ref }}
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}