name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud-analysis:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Backend Setup
      - name: Install Backend Dependencies
        working-directory: backend
        run: npm install

      - name: Configure Backend Coverage
        working-directory: backend
        run: |
          npm pkg set scripts.test="vitest run --coverage"
          npm pkg set scripts.pretest="rm -rf coverage"

      - name: Run Backend Tests
        working-directory: backend
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
        run: npm run pretest && npm test

      # Frontend/Cypress Setup (if needed for code analysis)
      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm install

      # SonarCloud Analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v4.1.0
        with:
          args: >
            -Dsonar.organization=Mohamed-Redouane
            -Dsonar.projectKey=redouane
            -Dsonar.sources=backend,frontend
            -Dsonar.tests=backend
            -Dsonar.test.inclusions=backend/**/*.test.ts
            -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**
            -Dsonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
            -Dsonar.qualitygate.wait=true
            -Dsonar.branch.name=${{ github.event.pull_request.head.ref || github.ref_name }}