name: SonarCloud Analysis

on:
  push:
    branches:
      - main  # Runs on main branch
  pull_request:
    types: [opened, synchronize, reopened]  # Also analyze PRs

jobs:
  sonar:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # ✅ Install Backend Dependencies
      - name: Install Backend Dependencies
        working-directory: backend
        run: npm install

      # ✅ Install Frontend Dependencies
      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm install

      # ✅ Run Backend Tests with Coverage
      - name: Run Backend Tests with Coverage
        working-directory: backend
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
        run: npm test -- --coverage

      # ✅ Run Frontend Tests with Coverage
      - name: Run Frontend Tests with Coverage
        working-directory: frontend
        run: npm test -- --coverage || echo "Frontend tests failed, continuing SonarCloud analysis"

      # ✅ Run SonarCloud Analysis
      - name: SonarCloud Analysis
        run: |
          npx sonarqube-scanner \
            -Dsonar.organization=Mohamed-Redouane \
            -Dsonar.projectKey=mohamed-redouane \
            -Dsonar.sources=backend,frontend \
            -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/** \
            -Dsonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
