name: Automated Testing Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend-and-cypress-tests:
    name: Run Frontend and Cypress Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install

      - name: Start Backend Server
        working-directory: ./backend
        run: npm run dev > backend.log 2>&1 &
        env:
          NODE_ENV: test
          PORT: 3000
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Show Backend Logs
        run: cat backend.log

      - name: Debug Backend Health
        run: curl -v http://localhost:3000 || echo "Backend not responding"

      - name: Wait for Backend Server
        run: wait-on --verbose http://localhost:3000 --timeout 60000

      - name: Start Frontend Server
        working-directory: ./frontend
        run: npm run dev > frontend.log 2>&1 &
        env:
          NODE_ENV: test

      - name: Show Frontend Logs
        run: cat frontend.log

      - name: Debug Frontend Health
        run: curl -v http://localhost:5173 || echo "Frontend not responding"

      - name: Wait for Frontend Server
        run: wait-on --verbose http://localhost:5173 --timeout 60000

      - name: Run Cypress Tests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx cypress run

